### ISSUE TITLE
colours are gone

### ISSUE THREAD

**Issue by amitpande74** [JoachimGoedhart/VolcaNoseR#10]
Dear Joachim,

The webapp as well as the standalone does not display colours anymore.
[edgeR_DLX5_high.txt](https://github.com/JoachimGoedhart/VolcaNoseR/files/6457779/edgeR_DLX5_high.txt)
attached is the input file.
Am I doing something wrong.
HELP.
regards,
Amit.

**Comment by JoachimGoedhart** [comment]
It seems that your data does not have a column with -log10(p-value) data. When added (calculated from the pvalue), I get a decent Volcano Plot.
![VolcaNoseR_2021-05-18 11_04_35](https://user-images.githubusercontent.com/39348589/118623763-da600480-b7c8-11eb-8a24-813249e976de.png)

Updated data:
[edgeR_DLX5_high.csv](https://github.com/JoachimGoedhart/VolcaNoseR/files/6499919/edgeR_DLX5_high.csv)

**Comment by amitpande74** [comment]
Hi@Joachim,
Thanks a lot for pointing it out.
