### ISSUE TITLE
Plots not loading

### ISSUE THREAD

**Issue by MaxTollenaere** [JoachimGoedhart/VolcaNoseR#11]
Hi Joachim,

Since today i am unable to see any plots in VolcaNoseR. Even when i try to plot the example data i get the following error message:
![error](https://user-images.githubusercontent.com/84081295/117977707-67224280-b331-11eb-8f68-f7f77dbc6f36.PNG)

It happens in chrome as well as microsoft edge.

**Comment by MaxTollenaere** [comment]
It works fine when i launch it via R by the way :)

**Comment by srimayeev** [comment]
I'm having the same issue  and error message :(

**Comment by JoachimGoedhart** [comment]
Thanks for bringing this to my attention - I'll check what's going on. In the meanwhile, you may use this site: https://goedhart.shinyapps.io/VolcaNoseR/

**Comment by JoachimGoedhart** [comment]
Resetting the server fixed it. The app is available again at: https://huygens.science.uva.nl/VolcaNoseR/
