### ISSUE TITLE
VolcaNoseR not working

### ISSUE THREAD

**Issue by katja-kiseljak-vassiliades** [JoachimGoedhart/VolcaNoseR#14]
Hello,
I am trying to use VolcaNoseR. I went on website https://huygens.science.uva.nl/VolcaNoseR/, several times today and get 502 Bad Gateway. Just wanted to check if this platform is still active?
Thanks,
Katja

**Comment by JoachimGoedhart** [comment]
Hi Katja,

Probably something wrong with the server, I'll look into it. In the meanwhile you can use the app at these mirrors:
https://huygens.science.uva.nl/VolcaNoseR2/
https://goedhart.shinyapps.io/VolcaNoseR/

Cheers,
Joachim.

**Comment by elvavidya** [comment]
I second this. https://goedhart.shinyapps.io/VolcaNoseR/ is accessible but after uploading my file, I got "Disconnected from server" error. 
https://huygens.science.uva.nl/VolcaNoseR2/ worked well for me. 

Thanks, 
Elva

**Comment by JoachimGoedhart** [comment]
Thanks Elva, for the info.
Usually the "Disconnected from server" is caused by wrong file format (or unexpected characters in the file), but in that case it would throw an error on both apps. Not sure what's going on, but if you want me to check it, you may send me yoru data (by email).

Cheers,
Joachim.

**Comment by katja-kiseljak-vassiliades** [comment]
Hi Joachim,
Many thanks for the quick reply. I was able to load the data using and run the plot with https://huygens.science.uva.nl/VolcaNoseR2/. 
Regarding the other ones, https://goedhart.shinyapps.io/VolcaNoseR/ - says "Disconnected from server". And the original URL (https://huygens.science.uva.nl/VolcaNoseR/) is still not working.
Many thanks for your help and for creating this cool app!
Katja

**Comment by JoachimGoedhart** [comment]
Hi Katja,
The original server, https://huygens.science.uva.nl/VolcaNoseR/ is live again. Do not hesitate to ping me if it goes down again.
Cheers,
Joachim.
