### ISSUE TITLE
Correct package installation instructions

### ISSUE THREAD

**Issue by jessica-cox** [JoachimGoedhart/VolcaNoseR#15]
The app is really useful! The install instructions I used were:
`install.packages(c("shiny", "ggplot2", "dplyr", "magrittr", "ggrepel", "DT", "shinycssloaders", "RCurl", "readxl", "ggiraph", "tidyverse"))`

I needed the extra packages _ggiraph_ and _tidyverse_, and needed to pass a vector of package names to the function. The instructions on here didn't work for me.

**Comment by JoachimGoedhart** [comment]
Thanks for the kind words and sharing what worked for you. I will update the instructions accordingly (Note that the ggplot2, dplyr, magrittr packages are also part of tidyverse and do not need installation when tidyverse is used).

Cheers,
Joachim.
