### ISSUE TITLE
Problem to download html file (interactive figure)

### ISSUE THREAD

**Issue by gardunorr** [JoachimGoedhart/VolcaNoseR#16]
When I download html file from iPlot, I have a server error. Inversely, I have no problem when I downloaded a html files from example 1 or 2....

What's happen ?

Thanks

**Comment by JoachimGoedhart** [comment]
Thanks for the message, which site are you using?
Does downloading the PNG/PDF work?

Cheers,
Joachim.


On 30 Jan 2024, at 11:09, gardunorr ***@***.******@***.***>> wrote:



When I download html file from iPlot, I have a server error. Inversely, I have no problem when I downloaded a html files from example 1 or 2....

What's happen ?

Thanks

**Comment by gardunorr** [comment]
I use: https://goedhart.shinyapps.io/VolcaNoseR/
I have no problem with .pdf or .png files.

Alain

**Comment by JoachimGoedhart** [comment]
And the error occurs when you try to download an HTML from the ‘iPlot’ tab?
I cannot reproduce the error with some of my own data (Using Firefox). Perhaps you can email your data, so I can troubleshoot?

Cheers,
Joachim.



__________________________________________

Dr. Joachim Goedhart
Assistant Professor
Section Molecular Cytology
SILS | University of Amsterdam

Web: https://joachimgoedhart.github.io/
Twitter: @joachimgoedhart
DataViz Apps: https://huygens.science.uva.nl<https://huygens.science.uva.nl/>
__________________________________________




On 30 Jan 2024, at 12:09, gardunorr ***@***.******@***.***>> wrote:



I use: https://goedhart.shinyapps.io/VolcaNoseR/
I have no problem with .pdf or .png files.

Alain

**Comment by gardunorr** [comment]
OK I send you my data
