### ISSUE TITLE
Website Down

### ISSUE THREAD

**Issue by CynthiaS07** [JoachimGoedhart/VolcaNoseR#17]
Continuosly disconnects from server.

**Comment by CynthiaS07** [comment]
To clarify, the issue is with uploading excel files. It immediately disconnects from server.

**Comment by CynthiaS07** [comment]
Also, unable to label as many points as I want. Limited to 5-6.

**Comment by JoachimGoedhart** [comment]
Hi, to resolve the issue could you:
-Tell me which HTML address are you using? Did you try alternative addresses?
-Send me the data by email, contact info: https://joachimgoedhart.github.io/

**Comment by Garrythepro** [comment]
https://goedhart.shinyapps.io/VolcaNoseR/

**Comment by Garrythepro** [comment]
https://amsterdamstudygroup.shinyapps.io/VolcaNoseR/

**Comment by JoachimGoedhart** [comment]
We've migrated the server. All seems to be working well. Another alternative is:
https://huygens.science.uva.nl/VolcaNoseR2/
