### ISSUE TITLE
Website not working 

### ISSUE THREAD

**Issue by margotcj** [JoachimGoedhart/VolcaNoseR#18]
Hello!

I've been using this platform for the last couple of months for my PhD thesis and found it very useful, however, when I attempted to access the site today it wouldn't load. Would you be able to check please?

Thanks,

Margot

**Comment by JoachimGoedhart** [comment]
Dear Margot,

Thanks for the interest. We have updated the server today and initially it worked without any problems, but there seems to be an issue now. We'll look into it, in the meantime you may use:
https://amsterdamstudygroup.shinyapps.io/VolcaNoseR/
Or:
https://goedhart.shinyapps.io/VolcaNoseR/

Best regards,
Joachim.

**Comment by JoachimGoedhart** [comment]
It is working again, the server (https://huygens.science.uva.nl/) is accessible now.

Happy plotting!

**Comment by margotcj** [comment]
thanks!!
