### ISSUE TITLE
Error: unable to find an inherited method for function ‘select’ for signature ‘"tbl_df

### ISSUE THREAD

**Issue by etiennedanis** [JoachimGoedhart/VolcaNoseR#8]
Hello,
When I try to use your shiny app, just using your example data, I get the following error message when I click on the tab 'Plot':
**Error: unable to find an inherited method for function ‘select’ for signature ‘"tbl_df"’**
Is there anything I can do no my side to fix this?
Thank you very much in advance.
Best, Etienne

**Comment by JoachimGoedhart** [comment]
Hi Etienne,

Thanks for the interest. Honestly, I'm not sure what's causing this error message. The Shiny errors can be rather cryptic....
Do you run the app from Rstudio? And is the example data present in the same directory as the app?

Best regards,
Joachim

**Comment by etiennedanis** [comment]
Hi Joachim,
It was RStudio. Launched from R in the terminal, I did not get this error message.
Thank you very much for the prompt response and solution!
Best,
Etienne
