### ISSUE TITLE
Inverted volcano plot

### ISSUE THREAD

**Issue by etiennedanis** [JoachimGoedhart/VolcaNoseR#9]
Hi Joachim,
I am getting a volcano plot but it is inverted: Instead of looking like a V, it looks like an A. 
I got normal volcano/V shape doing volcano plots with ggplot2 or EnhancedVolcano with my data set.
Is there any option I should select or unselect? 
Also, is there an option to select a specific adjusted p-value?
Thank you very much in advance.
Best,
Etienne

**Comment by JoachimGoedhart** [comment]
That's weird - did you select the right columns for plotting?
You can send me the data by email and I'd be happy to take a look!
Cheers,
Joachim.

**Comment by farhan-lab** [comment]
Hi,

I have the same issue of the inverted plots. Could you share what right columns should be plotted? I have used the X column as fold change and  for Y axis, I select P value, but my volcano plot is inverted.

Thanks,
Farhan

**Comment by JoachimGoedhart** [comment]
Please note that the app only plots the data and does no processing. From what I understand, you plot p-values, but the standard Volcano plot uses -log[p-value].

I hope this helps. If not, you could send me the data by email and I'd be happy to take a look!
Cheers,
Joachim.
